#cloud-config
# vim:syntax=yaml
users:
  - default
  - name: romaxa55
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_public_key}

packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - containerd
  - podman
  - qemu-guest-agent

# Let iptables see bridged traffic
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
write_files:
- path: /etc/modules-load.d/k8s.conf
  content: |
    br_netfilter

- path: /etc/sysctl.d/k8s.conf
  content: |
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.ipv4.ip_forward = 1

- path: /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
  content: |
    # Enabling password authentication
    PasswordAuthentication yes          

runcmd:
- systemctl restart sshd
- systemctl enable --now qemu-guest-agent
- sysctl --system
- echo "About to run dmgw"
- modprobe br_netfilter # Load br_netfilter module.
- curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
- echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
- sudo apt-get update
- sudo apt-get install -y kubelet kubeadm kubectl
- sudo apt-mark hold kubelet kubeadm kubectl
- sudo systemctl enable --now kubelet  

scripts-user:
- /var/lib/cloud/instance/scripts/runcmd